apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  IDAM_S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  ENABLE_DB_MIGRATE: "false"
  USER_PROFILE_S2S_AUTHORISED_SERVICES: "ccd_data,ccd_definition,ccd_admin"
  APPINSIGHTS_INSTRUMENTATIONKEY: 'fake-key'
