java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: 250Mi
  devmemoryLimits: 1024Mi
  devcpuRequests: 250m
  devcpuLimits: 1500m
  keyVaults:
    ccd:
      resourceGroup: ccd-shared
  environment:
    USER_PROFILE_DB_HOST: "{{ .Release.Name }}-postgresql"
    USER_PROFILE_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    USER_PROFILE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
    USER_PROFILE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    USER_PROFILE_DB_OPTIONS: "?stringtype=unspecified"
  postgresql:
    enabled: true
