name: Suppressions

on:
  push:
    branches:
      - test-fix-workflow-suppression
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_CCD_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_CCD_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Set up Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Run OWASP Dependency Check with Gradle
        run: ./gradlew dependencyCheckAggregate -Dnvd.api.key=58942d4f-1548-4b6f-8629-e7eb19ea263a -Dnvd.api.delay=3000
      - name: Run suppressCves
        run: ./gradlew suppressCves
      - name: Run cleanSuppressions
        run: ./gradlew cleanSuppressions
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Suppressing CVE - Actions"
          branch: master
