name: Publish Swagger Specs

on:
  push:
    branches:
      - master
      - test-swagger-publish-off-master
      - CCD-3916_Github_Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Cache
        uses: actions/cache@v3.0.11
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run Swagger Publisher
        run: ./gradlew test --tests uk.gov.hmcts.ccd.swagger.SwaggerPublisher
      - name: Commit to repository
        run: |
          mkdir swagger-staging
          cd swagger-staging
          git init
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub action"
          git remote add upstream https://${{ secrets.GH_TOKEN }}@github.com/hmcts/reform-api-docs.git
          git pull upstream master
          repo=`echo "$GITHUB_REPOSITORY" | cut -f2- -d/`
          echo "$(cat /tmp/swagger-specs.json)" > "docs/specs/$repo.json"
          git add "docs/specs/$repo.json"
          # Only commit and push if we have changes.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update spec for $repo#${GITHUB_SHA:7}"; git push --set-upstream upstream master)
